const c=document.getElementById("game"),ctx=c.getContext("2d"),VW=1280,VH=720,T=48,WW=4800,WH=3360;
const keys={up:false,down:false,left:false,right:false},cam={x:0,y:0},p={x:432,y:1632,r:14,speed:205,dir:1};
const stats={faith:72,authority:48,holiness:68,fasting:35,health:100,peace:62,wisdom:36,discernment:28,hunger:15,thirst:12};
const inv={"Bíblia":1,"Pão":4,"Água":4,"Pergaminho":2,"Madeira":6,"Lamparina":1};
const bars=[["✝ Fé","faith"],["🛡 Autoridade","authority"],["🕊 Santidade","holiness"],["🙏 Jejum","fasting"],["❤ Saúde","health"],["☮ Paz","peace"],["📖 Sabedoria","wisdom"],["👁 Discernimento","discernment"],["🍖 Fome","hunger"],["💧 Sede","thirst"]];
const trees=[],houses=[],npcs=[],flowers=[];let quest=0,clock=0,night=false,last=performance.now(),prayCD=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>Math.random()*(b-a)+a;
function say(t,ms=4500){let e=document.getElementById("message");e.innerHTML=t;e.style.display="block";clearTimeout(say.t);say.t=setTimeout(()=>e.style.display="none",ms)}
for(let i=0;i<260;i++){let x=rnd(50,WW-50),y=rnd(80,WH-50);if(Math.hypot(x-p.x,y-p.y)<500){i--;continue}trees.push({x,y,r:rnd(19,26)})}
for(let i=0;i<130;i++)flowers.push({x:rnd(20,WW-20),y:rnd(20,WH-20),r:rnd(1,3)});
function house(x,y,w,h,type){houses.push({x,y,w,h,type})}
house(384,1488,130,90,"casa");house(768,1392,140,100,"templo");house(624,1872,110,75,"cabana");house(1200,1152,125,85,"casa");house(3456,1632,150,100,"porto");
function npc(x,y,name,msg,kind){npcs.push({x,y,name,msg,kind,phase:rnd(0,7)})}
npc(960,1632,"Ancião","A missão começa com um passo de fé. Atravesse a floresta e procure o caminho para o porto.","elder");
npc(672,1632,"Maria","Quando o medo chegar, pare, respire e ore.","friend");npc(1152,1728,"Elias","Nem todo perigo será visível aos olhos. Peça discernimento.","friend");npc(3360,1632,"Marinheiro","Há um barco no porto. Quando estiver pronto, a travessia começará.","sailor");
function buildUI(){document.getElementById("bars").innerHTML=bars.map(([n,k])=>`<div class="barRow"><span>${n}</span><div class="bar"><div class="fill" id="b-${k}"></div></div><span id="v-${k}">0</span></div>`).join("")}
function updateUI(){bars.forEach(([n,k])=>{document.getElementById("b-"+k).style.width=clamp(stats[k],0,100)+"%";document.getElementById("v-"+k).textContent=Math.round(stats[k])})}
function blocked(x,y){if(x<20||y<20||x>WW-20||y>WH-20)return true;for(const t of trees)if((x-t.x)**2+(y-t.y)**2<(p.r+t.r-5)**2)return true;for(const h of houses){let cx=clamp(x,h.x-h.w/2,h.x+h.w/2),cy=clamp(y,h.y-h.h/2,h.y+h.h/2);if((x-cx)**2+(y-cy)**2<p.r*p.r)return true}return false}
function ground(){ctx.fillStyle="#466f3c";ctx.fillRect(0,0,VW,VH);ctx.save();ctx.translate(-cam.x,-cam.y);ctx.fillStyle="#b29262";ctx.fillRect(0,1645,WW,70);ctx.fillStyle="#2c6281";ctx.fillRect(2352,0,624,WH);ctx.fillStyle="#84633f";ctx.fillRect(2304,1590,720,96);ctx.fillStyle="#355c40";for(let i=0;i<WW;i+=180){ctx.beginPath();ctx.moveTo(i,430);ctx.lineTo(i+90,290+(i%130));ctx.lineTo(i+180,430);ctx.closePath();ctx.fill()}flowers.forEach(f=>{ctx.fillStyle="#d6c978aa";ctx.fillRect(f.x,f.y,f.r,f.r)});houses.forEach(drawHouse);trees.forEach(drawTree);npcs.forEach(drawNPC);drawPlayer();ctx.restore()}
function drawTree(t){ctx.fillStyle="#523721";ctx.fillRect(t.x-6,t.y+8,12,31);ctx.fillStyle="#163c24";ctx.beginPath();ctx.arc(t.x,t.y,27,0,7);ctx.fill();ctx.fillStyle="#23552e";ctx.beginPath();ctx.arc(t.x-17,t.y+8,19,0,7);ctx.arc(t.x+18,t.y+8,19,0,7);ctx.fill()}
function drawHouse(h){ctx.fillStyle="#795538";ctx.fillRect(h.x-h.w/2,h.y-h.h/2,h.w,h.h);ctx.fillStyle=h.type==="templo"?"#55545a":"#4e3026";ctx.beginPath();ctx.moveTo(h.x-h.w/2-9,h.y-h.h/2);ctx.lineTo(h.x,h.y-h.h/2-48);ctx.lineTo(h.x+h.w/2+9,h.y-h.h/2);ctx.closePath();ctx.fill();ctx.fillStyle="#2a211b";ctx.fillRect(h.x-13,h.y+8,26,42);ctx.fillStyle="#e5cf80";ctx.font="29px serif";ctx.textAlign="center";ctx.fillText(h.type==="templo"?"✝":"⌂",h.x,h.y-7)}
function drawNPC(n){ctx.save();ctx.translate(n.x,n.y+Math.sin(performance.now()/500+n.phase));ctx.fillStyle=n.kind==="elder"?"#b99442":n.kind==="sailor"?"#607f8c":"#7d9dad";ctx.fillRect(-11,-1,22,35);ctx.fillStyle="#c98e63";ctx.beginPath();ctx.arc(0,-13,11,0,7);ctx.fill();ctx.fillStyle="#fff";ctx.font="12px Arial";ctx.textAlign="center";ctx.fillText(n.name,0,-31);ctx.restore()}
function drawPlayer(){ctx.save();ctx.translate(p.x,p.y);ctx.scale(p.dir,1);ctx.fillStyle="#c98e63";ctx.beginPath();ctx.arc(0,-18,12,0,7);ctx.fill();ctx.fillStyle="#e8dfc6";ctx.fillRect(-13,-5,26,38);ctx.fillStyle="#65452d";ctx.fillRect(-15,-29,30,7);ctx.strokeStyle="#e4c35d";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(10,-1);ctx.lineTo(20,25);ctx.stroke();ctx.restore()}
function light(){ctx.fillStyle=night?"rgba(5,9,24,.50)":"rgba(255,220,130,.06)";ctx.fillRect(0,0,VW,VH)}
function move(dt){let dx=(keys.right?1:0)-(keys.left?1:0),dy=(keys.down?1:0)-(keys.up?1:0);if(!dx&&!dy)return;let l=Math.hypot(dx,dy);dx/=l;dy/=l;let nx=p.x+dx*p.speed*dt,ny=p.y+dy*p.speed*dt;if(!blocked(nx,p.y))p.x=nx;if(!blocked(p.x,ny))p.y=ny;if(dx)p.dir=dx>0?1:-1}
function near(){let b=null,d0=88;for(const n of npcs){let d=Math.hypot(n.x-p.x,n.y-p.y);if(d<d0){b=n;d0=d}}return b}
function dialogue(s,t){document.getElementById("speaker").textContent=s;document.getElementById("dialogueText").innerHTML=t;document.getElementById("dialogue").style.display="grid"}
function interact(){let n=near();if(!n){say("Aproxime-se de um personagem para conversar.");return}dialogue(n.name,n.msg);if(n.kind==="elder"&&quest===0){quest=1;stats.faith+=10;stats.wisdom+=7;document.getElementById("questBody").innerHTML="✓ Ancião encontrado.<br><br>Atravesse a floresta e chegue ao porto."}else if(n.kind==="sailor"&&quest===1){quest=2;document.getElementById("questBody").innerHTML="✓ Chegou ao porto.<br><br>A próxima etapa será a travessia do oceano."}}
function pray(){if(prayCD>0){say("Aguarde um pouco antes de orar novamente.");return}prayCD=7;stats.faith=clamp(stats.faith+5,0,100);stats.peace=clamp(stats.peace+9,0,100);stats.authority=clamp(stats.authority+3,0,100);stats.discernment=clamp(stats.discernment+1,0,100);say("<b>🙏 ORAÇÃO</b><br>Você busca a Deus.<br>Fé +5 • Paz +9 • Autoridade +3 • Discernimento +1")}
function sleep(){if(!night){say("🌙 Ainda é dia.");return}stats.health=clamp(stats.health+22,0,100);stats.peace=clamp(stats.peace+10,0,100);dialogue("SONHO ESPIRITUAL","Você vê uma grande luz sobre a floresta. Uma voz diz: “Não temas. Continue o caminho.”")}
function invShow(){document.getElementById("items").innerHTML=Object.entries(inv).map(([k,v])=>`<div class="item"><span>${k}</span><b>${v}</b></div>`).join("");document.getElementById("inventory").style.display="grid"}
document.getElementById("dialogueOk").onclick=()=>document.getElementById("dialogue").style.display="none";document.querySelector(".close").onclick=()=>document.getElementById("inventory").style.display="none";document.getElementById("tPray").onclick=pray;document.getElementById("tInv").onclick=invShow;document.getElementById("tInteract").onclick=interact;
addEventListener("keydown",e=>{let k=e.key.toLowerCase();if(k==="w"||k==="arrowup")keys.up=true;if(k==="s"||k==="arrowdown")keys.down=true;if(k==="a"||k==="arrowleft")keys.left=true;if(k==="d"||k==="arrowright")keys.right=true;if(k==="e")interact();if(k==="r")pray();if(k==="i")invShow();if(k===" "&&night)sleep()});addEventListener("keyup",e=>{let k=e.key.toLowerCase();if(k==="w"||k==="arrowup")keys.up=false;if(k==="s"||k==="arrowdown")keys.down=false;if(k==="a"||k==="arrowleft")keys.left=false;if(k==="d"||k==="arrowright")keys.right=false});
document.querySelectorAll(".stick button").forEach(b=>{let k=b.dataset.key;b.addEventListener("pointerdown",e=>{e.preventDefault();keys[k]=true});["pointerup","pointercancel","pointerleave"].forEach(ev=>b.addEventListener(ev,()=>keys[k]=false))});
function loop(now){let dt=Math.min(.05,(now-last)/1000);last=now;clock+=dt;night=(clock%90)>55;prayCD=Math.max(0,prayCD-dt);stats.hunger=clamp(stats.hunger+dt*.65,0,100);stats.thirst=clamp(stats.thirst+dt*.8,0,100);if(stats.hunger>90||stats.thirst>90)stats.health=clamp(stats.health-dt*.8,0,100);move(dt);cam.x=clamp(p.x-VW/2,0,WW-VW);cam.y=clamp(p.y-VH/2,0,WH-VH);ground();light();updateUI();requestAnimationFrame(loop)}
buildUI();updateUI();setTimeout(()=>document.getElementById("loading").style.display="none",500);say("<b>🌅 O CHAMADO</b><br>Explore a vila e encontre o Ancião.");requestAnimationFrame(loop);